name: lunarr
version: 11.0.0
confinement: strict
base: core22
# Required but managed manually via Snapcraft dashboard
summary: summary
description: description
slots:
  dbus-lunarr:
    interface: dbus
    bus: session
    name: app.lunarr.lunarr
apps:
  lunarr:
    command: lunarr
    extensions:
    - gnome
    plugs:
    - home
    - network
    slots:
    - dbus-lunarr
parts:
  zenity:
    plugin: nil
    stage-packages:
    - zenity
  lunarr:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
