name: Build Mobile
run-name: "Build Mobile Release: ${{ inputs.flavor || github.sha }}"

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      flavor:
        description: Build Flavor
        required: true
        default: edge
        type: choice
        options:
          - edge
          - beta
          - stable

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml
    with:
      flavor: ${{ inputs.flavor }}

  build-android:
    name: Build Android
    needs: [prepare]
    uses: ./.github/workflows/build_android.yml
    with:
      build-number: ${{ needs.prepare.outputs.build-number }}
    secrets:
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

  build-ios:
    name: Build iOS
    needs: [prepare]
    uses: ./.github/workflows/build_ios.yml
    with:
      build-number: ${{ needs.prepare.outputs.build-number }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      IOS_CODESIGNING_IDENTITY: ${{ secrets.IOS_CODESIGNING_IDENTITY }}
      MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_SSH_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
